-- COMANDOS PARA CRIAR BD
-- 1.Criar banco de dados
Create Database CLINICA_MEDICA_GABRIELLI;
create database if not exists CLINICA_MEDICA_GABRIELLI;

CREATE DATABASE BANCO_DADOS;

-- Ativar BD E ATUALIZAR SHCEMAS
-- 2.
USE CLINICA_MEDICA_GABRIELLI;

-- CRIAR TABELAS
-- 3.
CREATE TABLE IF NOT EXISTS PACIENTES(
ID_PACIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME_PACIENTE VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
DATA_NASCIMENTO DATE NOT NULL,
EMAIL VARCHAR(100),
TELEFONE VARCHAR(15),
CONVENIO ENUM ('Sim', 'Não') NOT NULL
);

CREATE TABLE IF NOT EXISTS TABELA(
ARIBUTO  VARCHAR(20),
ATRIBUT VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
ID_FUNCIONARIO INT PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
TELEFONE VARCHAR(15),
SALARIO DECIMAL(5,2) NOT NULL DEFAULT 0.00

);
CREATE TABLE IF NOT EXISTS PACIENTES02(
ID_PACIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME_PACIENTE VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
DATA_NASCIMENTO DATE NOT NULL,
EMAIL VARCHAR(100),
TELEFONE VARCHAR(15),
CONVENIO ENUM ('Sim', 'Não') NOT NULL
);

-- ALTERAR INFORMAÇÕES DA TABELA
-- ALTER TABLE
-- ADICIONAR UM CAMPO (ATRIBUTO) OU COLUNA NA TABELA 
ALTER TABLE FUNCIONARIOS ADD EMAIL VARCHAR (100) NOT NULL;

-- ALTERAR TIPO DE DADOS DE CAMPO (ATRIBUTOS) OU COLUNA NA TABELA

ALTER TABLE FUNCIONARIOS MODIFY EMAIL VARCHAR(50) NOT NULL;

-- APAGAR O CAMPO (ATRIBUTO) OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOS DROP COLUMN EMAIL;

-- RENOMEAR TABELAS
RENAME TABLE FUNCIONARIOS TO FUNCIONARIOSS;

-- APAGAR DADOS DA TABELA
TRUNCATE TABLE FUNCIONARIOSS;
TRUNCATE TABLE PACIENTES;
TRUNCATE TABLE PACIENTES02;
-- APAGAR BD
DROP DATABASE CLINICA_MEDICA_GABRIELLI;

-- APAGAR TABELAS
DROP TABLES FUNCIONARIOSS;

-- MOSTRAR TABELAS NO BD
SHOW TABLES;

-- - ----------------------------------

-- INSERIR DADOS NO BD
INSERT INTO FUNCIONARIOSS (ID_FUNCIONARIO,NOME_FUNCIONARIO,CPF,TELEFONE,SALARIO,EMAIL)
VALUE(1,'GABRIELLI','123.456.789-10','(19)88721-9862',200,'gabrielliaraujo698@gmail.com');

INSERT INTO PACIENTES (ID_PACIENTE,NOME_PACIENTE,CPF,DATA_NASCIMENTO,EMAIL,TELEFONE,CONVENIO)
VALUE (DEFAULT, 'GABRIELLI', '153.456.722-34','2010-02-19','gabrielliaraujo509@gmail.com','(19)87693-9864','SIM');

INSERT INTO PACIENTES02 (ID_PACIENTE,NOME_PACIENTE,CPF,DATA_NASCIMENTO,EMAIL,TELEFONE,CONVENIO)
VALUE ('3', 'ISABELA', '153.454.222-34','2010-05-20','isabelaaraujo302@gmail.com','(19)87493-9874',default);
-- CONSULTAR DADOS NO BD
SELECT * FROM FUNCIONARIOSS, PACIENTES, PACIENTES02
