
-- PROJETO SMARTCOFFE

-- CRIAR BANCO DE DADOS
-- ATIVAR BANCO DE DADOS
-- CRIAR TABELAS

CREATE DATABASE PROJETO_SMARTCOFFE;
CREATE DATABASE IF NOT EXISTS PROJETO_SMARTCOFFE;

USE PROJETO_SMARTCOFFE;

CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTES VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
DATA_NASCIMENTO DATE NOT NULL,
EMAIL VARCHAR(100),
TELEFONE VARCHAR(15),
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
ID_FUNCIONARIO INT PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
SETOR VARCHAR(15),
SALARIO DECIMAL(5,2) NOT NULL DEFAULT 0.00,
CARGO VARCHAR(30) NOT NULL,
TELEFONE VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS PEDIDOS(
ID_PEDIDOS INT PRIMARY KEY,
CPF VARCHAR(14) NOT NULL UNIQUE,
SETOR VARCHAR(15),
SALARIO DECIMAL(5,2) NOT NULL DEFAULT 0.00,
CARGO VARCHAR(30) NOT NULL,
TELEFONE VARCHAR(15)
);


SELECT * FROM FUNCIONARIOSS, PACIENTES, PACIENTES02